"""Arrumando erro

Revision ID: 24f8b2052940
Revises: 19e5e464801b
Create Date: 2022-02-04 13:40:38.925977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f8b2052940'
down_revision = '19e5e464801b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamanhos', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('tamanhos')

    # ### end Alembic commands ###
