"""erro de digitacao

Revision ID: f5db8b4d8b67
Revises: 24f8b2052940
Create Date: 2022-02-04 14:26:43.633132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5db8b4d8b67'
down_revision = '24f8b2052940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
